FROM mcr.microsoft.com/dotnet/sdk:10.0

RUN apt-get update && apt-get install -y curl unzip && \
    curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

EXPOSE 5060
EXPOSE 5061
EXPOSE 10009

# Non-interactive mode for Docker
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1 \
    DOTNET_NOLOGO=true \
    DOTNET_GENERATE_ASPNET_CERTIFICATE=false \
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true \
    DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true \
    DOTNET_EnableDiagnostics=0 \
    DOTNET_SKIP_WORKLOAD_INTEGRITY_CHECK=true \
    ASPNETCORE_ENVIRONMENT=Development \
    ASPNETCORE_URLS=http://+:5060

COPY entrypoint.dev.sh /entrypoint.dev.sh
RUN chmod +x /entrypoint.dev.sh
ENTRYPOINT ["/entrypoint.dev.sh"]
